# Generated by Django 3.1.2 on 2020-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='파일 경로'),
        ),
    ]
