# Generated by Django 3.1.2 on 2020-10-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_inspection', '0002_auto_20201029_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
