# Generated by Django 3.1.2 on 2020-11-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_inspection', '0003_remove_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='documents/')),
                ('file_path', models.FileField(null=True, upload_to='documents/', verbose_name='파일 경로')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
