# Generated by Django 3.1.3 on 2020-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_inspection', '0004_auto_20201111_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
