# Generated by Django 3.1.2 on 2020-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=20, verbose_name='사원번호')),
                ('username', models.CharField(max_length=20, verbose_name='이름')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
